import jwt from 'jsonwebtoken'
// If i want to like a post then response come to auth and if the user valid then its like otherwise not like 
// so thats why we will use that allows to perform next operation

const auth = async (req, res, next) => {
    if (req.headers.authorization) {
        try {
            const token = req.headers.authorization.split(" ")[1]
            // if the token length is less then 500 then its our own token otherwise its google token
            const isCustomAuth = token.length < 500

            let decodedData;
            if (token && isCustomAuth) {
                decodedData = jwt.verify(token, 'test')
                req.userId = decodedData?.id
            }
            else {
                decodedData = jwt.decode(token)
                // sub is id that will generated by google for each account
                req.userId = decodedData?.sub
            }
            next();

        } catch (error) {
            res.status(500).json({ message: error.message })
        }
    } else {
        res.status(300).json({ message: 'Invalid headers' })
    }

}

export default auth;